WHITESPACE = _{ (" " | NEWLINE ) }

num = @{
    "-"?
    ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
    ~ ("." ~ ASCII_DIGIT*)?
    ~ (^"e" ~ ("+" | "-")? ~ ASCII_DIGIT+)?
    ~ !(ASCII_ALPHA)
}

operator = @{"+" | "-" | "*" | "/" | "%" | "^" | "==" | "!=" | ">=" | "<=" | "<" | ">" }

symbol = @{ 
    ASCII_ALPHA+
    ~ (ASCII_ALPHA | ASCII_DIGIT | "_")*
}

list = { "(" ~ expr* ~ ")" }

expr = { num | symbol | operator | list }

risp = { SOI ~ expr* ~ EOI }